name: Build Rosyad APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # <--- WAJIB 22.04 (ULAH UBAH IEU)
    
    steps:
      - uses: actions/checkout@v2

      # 1. BERSIHKEUN MEMORI (Supaya teu error 'Disk Full')
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # 2. INSTALL ALAT PERANG (VERSI LENGKAP)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libncurses5 \
            libncursesw5 \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            openjdk-17-jdk \
            zip \
            unzip

      # 3. SETTING JAVA (WAJIB JAVA 17)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. INSTALL BUILDOZER & CYTHON
      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer==1.5.0 cython==0.29.33 virtualenv

      # 5. DOWNLOAD ICON
      - name: Download Icon
        run: wget -O icon.png "https://lh3.googleusercontent.com/d/181EO8tS_ECc0pO9zzk1lr3MsDh_Pbqu7"

      # 6. BUILD APK (FIX BROKEN PIPE)
      - name: Build APK
        run: |
          # Paksa persetujuan SDK heula supaya teu butuh 'yes |'
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # Jalankeun Buildozer
          yes | buildozer android debug

      # 7. UPLOAD HASIL
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RosyadStore-APK
          path: bin/*.apk