
name: Build Rosyad APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Siapkeun Mesin
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libncurses5 libncursesw5 libtinfo5 cmake libffi-dev libssl-dev autoconf libtool openjdk-17-jdk unzip
      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer==1.5.0 cython==0.29.33 virtualenv
      - name: Download Icon
        run: wget -O icon.png "https://lh3.googleusercontent.com/d/181EO8tS_ECc0pO9zzk1lr3MsDh_Pbqu7"
      - name: Masak APK
        run: |
          yes | buildozer android debug
      - name: Pindahkeun APK (Fix Double Zip)
        run: |
          mv bin/*.apk .
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Rosyad-App
          path: "*.apk"
