
name: Build Rosyad APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libncurses5 libncursesw5 libtinfo5 cmake libffi-dev libssl-dev autoconf libtool openjdk-17-jdk zip unzip p7zip-full
      - name: Setup Java
        uses: actions/setup-java@v3
        with: { distribution: 'temurin', java-version: '17' }
      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer==1.5.0 cython==0.29.33 virtualenv
      - name: Build APK
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | buildozer android debug
      - name: Compress to 7z
        run: |
          cd bin
          7z a -t7z -m0=lzma2 -mx=5 apk_result.7z *.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RosyadStore-APK
          path: bin/apk_result.7z
