name: Build Rosyad APK
on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Siapkan Mesin
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev openjdk-17-jdk unzip autoconf libtool pkg-config libncurses5 libtinfo5

      - name: Install Buildozer
        run: pip3 install --upgrade buildozer cython==0.29.33 virtualenv

      - name: Download Icon Otomatis
        run: wget -O icon.png "https://lh3.googleusercontent.com/d/181EO8tS_ECc0pO9zzk1lr3MsDh_Pbqu7"

      - name: Mulai Masak APK
        run: yes | buildozer android debug

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: RosyadStore-APK
          path: bin/*.apk
